# Generated by Django 5.1.4 on 2025-01-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
