# Generated by Django 5.1.4 on 2025-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")],
                        max_length=7,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mail_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
            ],
            options={
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Ф.И.О. клиента рассылки",
                        max_length=250,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получателя рассылки",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_sending_at",
                    models.DateTimeField(verbose_name="Дата и время начала рассылки"),
                ),
                (
                    "end_sending_at",
                    models.DateTimeField(
                        verbose_name="Дата и время окончания рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершена"),
                            ("created", "Создана"),
                            ("started", "Запущена"),
                        ],
                        default="created",
                        max_length=9,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["message", "owner"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Введите тему",
                        max_length=250,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите сообщение", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
                "ordering": ["subject"],
            },
        ),
    ]
