# Generated by Django 5.1.4 on 2025-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_sending_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время начала рассылки"
            ),
        ),
    ]
