# Generated by Django 5.1.4 on 2025-01-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0004_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["message", "owner"],
                "permissions": [("can_finish_mailing", "Can finish mailing")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
